KLTN_FreshShop/Controllers/footerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KLTN_FreshShop.Controllers
{
    public class footerController : Controller
    {
        // GET: footer
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult dscuahang()
        {
            return View();
        }
        public ActionResult hdmuahang()
        {
            return View();
        }
        public ActionResult csdoitra()
        {
            return View();
        }
    }
}

KLTN_FreshShop/Views/Shared/_DanhMuc.cshtml
@using KLTN_FreshShop.Models;
@{
    KLTNEntities db = new KLTNEntities();
    var dsloai = db.LoaiSPs.ToList();
}
<div class="container">
    <div class="row">
        <div class="col-lg-3">
            <div class="hero__categories">
                <div class="hero__categories__all">
                    <i class="fa fa-bars"></i>
                    <span>Danh Mục</span>
                </div>
                <ul>
                    <li><a href="#"><img src="~/Lib/img/megamenu_item_icon1.jpg" />&nbsp; Dinh dưỡng thiết yếu</a></li>
                    <li><a href="@Url.Action("store_grid","SanPham", new { ma = 4})"><img src="~/Lib/img/megamenu_item_icon2.jpg" />&nbsp; Rau hữu cơ</a></li>
                    <li><a href="@Url.Action("store_grid","SanPham", new { ma = 5})"><img src="~/Lib/img/megamenu_item_icon3.jpg" />&nbsp; Rau củ an toàn</a></li>
                    <li><a href="@Url.Action("store_grid","SanPham", new { ma = 6})"><img src="~/Lib/img/megamenu_item_icon4.jpg" />&nbsp; Thịt cá dân dã</a></li>
                    <li><a href="@Url.Action("store_grid","SanPham", new { ma = 7})"><img src="~/Lib/img/megamenu_item_icon5.jpg" />&nbsp; Trái cây</a></li>
                    <li><a href="#"><img src="~/Lib/img/megamenu_item_icon6.jpg" />&nbsp; Đồ sơ chế</a></li>
                    <li><a href="@Url.Action("store_grid","SanPham", new { ma = 9})"><img src="~/Lib/img/megamenu_item_icon7.jpg" />&nbsp; Hải sản</a></li>
                    <li><a href="@Url.Action("store_grid","SanPham", new { ma = 10})"><img src="~/Lib/img/megamenu_item_icon8.jpg" />&nbsp; Hàng khô</a></li>
                    @*@foreach (var item in dsloai)
                        {
                            <li><a href="@Url.Action("store_grid","Sanpham")">@item.Ten</a></li>
                        }*@
                </ul>
            </div>
        </div>
        <div class="col-lg-9">
            <div class="hero__search">
                <div class="hero__search__form">
                    <form action="@Url.Action("timkiem","SanPham")" method="post">
                        <div class="hero__search__categories">
                            Tất cả
                            <span class="arrow_carrot-down"></span>
                        </div>
                        <input type="text" name="txtsearch" placeholder="Bạn đang tìm kiếm sản phẩm gì?">
                        <button type="submit" class="site-btn">Tìm kiếm</button>
                    </form>
                </div>
                <div class="hero__search__phone">
                    <div class="hero__search__phone__icon">
                        <i class="fa fa-phone"></i>
                    </div>
                    <div class="hero__search__phone__text">
                        <h5>0999999999</h5>
                        <span>Hỗ trợ 24/7</span>
                    </div>
                </div>
            </div>

            <div class="hero__item set-bg">
                @*<div class="hero__text">
                        <p style="color:chartreuse;font-size:20px;">Miễn phí vân chuyển</p>
                        <a href="#" class="primary-btn">Mua Ngay</a>
                    </div>*@
                <img src="~/Lib/img/banner/bn11.jpg" />
            </div>
        </div>
    </div>
</div>

KLTN_FreshShop/Views/Shared/_Footer.cshtml
<div class="row">
    <div class="col-lg-4 col-md-6 col-sm-6">
        <div class="footer__about">
            <div class="footer__about__logo">
                <div class="col-lg-7">
                    <div class="header__logo">
                        <a href="./index.html"><img src="~/Lib/img/logotps.png" alt=""></a>
                    </div>
                </div>
            </div>
            <ul>
                <li>Chuỗi cửa hàng thực phẩm sạch</li>
                <li><img src="~/Lib/img/footer1/iconfinder_home_353416.png" />385 Lê Văn Việt, HCM</li>
                <li><img src="~/Lib/img/footer1/iconfinder_phone-call_2561306.png" /> Phone: 0999999999</li>
                <li><img src="~/Lib/img/footer1/iconfinder_67-gmail_1181190.png" /> Email: codedoan.com@gmail.com</li>
            </ul>
        </div>
    </div>
    <div class="col-lg-4 col-md-6 col-sm-6 offset-lg-1">
        <div class="footer__widget">
            <h5>HỖ TRỢ KHÁCH HÀNG</h5>
            <ul>
                <li><a href="@Url.Action("dscuahang","footer")">Danh sách cửa hàng</a></li>
                <li><a href="@Url.Action("hdmuahang","footer")">Hướng dẫn mua hàng</a></li>
                <li><a href="#">Chính sách thẻ thành viên</a></li>
                <li><a href="@Url.Action("csdoitra","footer")">Chính sách đổi, trả hàng</a></li>
            </ul>
        </div>
    </div>

    <div class="col-lg-3 col-md-12">
        <div class="footer__widget">
            <h5>FANPAGE FACEBOOK</h5>
            <div class="ftfacebook">
                <iframe name="f2cbcf6923eb318" data-testid="fb:page Facebook Social Plugin" title="fb:page Facebook Social Plugin" allowtransparency="true" allowfullscreen="true" scrolling="no" allow="encrypted-media" style="border: medium none; visibility: visible; width: 300px; height: 70px;" src="https://www.facebook.com/v6.0/plugins/page.php?adapt_container_width=false&amp;app_id=&amp;channel=https%3A%2F%2Fstaticxx.facebook.com%2Fx%2Fconnect%2Fxd_arbiter%2F%3Fversion%3D46%23cb%3Df1e5ee7092338f%26domain%3Dbactom.com%26origin%3Dhttps%253A%252F%252Fbactom.com%252Ff255eed3ea033e8%26relation%3Dparent.parent&amp;container_width=360&amp;height=400&amp;hide_cover=false&amp;href=https%3A%2F%2Fwww.facebook.com%2Fraubactom&amp;locale=vi_VN&amp;sdk=joey&amp;show_facepile=true&amp;small_header=true&amp;width=300" class="" width="300px" height="400px" frameborder="0"></iframe>
            </div>
            <div class="footer__widget__social">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-youtube"></i></a>
            </div>
        </div>
    </div>
</div>

KLTN_FreshShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    @*<meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - My ASP.NET Application</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@
    <meta charset="UTF-8">
    <meta name="description" content="Bán các loại sản phẩm về điện máy">
    <meta name="keywords" content="điện thoại samsung, thẻ sim, iphone">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@ViewBag.Title</title>
    <!-- Google Font -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@900&display=swap" rel="stylesheet">
    @*<link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">*@
    <!-- Css Styles -->
    <link rel="stylesheet" href="~/Lib/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="~/Lib/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="~/Lib/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="~/Lib/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="~/Lib/css/jquery-ui.min.css" type="text/css">
    <link rel="stylesheet" href="~/Lib/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="~/Lib/css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="~/Lib/css/style.css" type="text/css" />

</head>
<body>
    <div id="preloder">
        <div class="loader"></div>
    </div>
    <header class="header">
        <div class="header__top">
            @*//top website*@
            @Html.Partial("_headerTop")
        </div>
        @*logo và menu*@
        <div id="topmenu">
            @Html.Partial("_TopMenu")
        </div>
    </header>
    <section class="hero">
        @Html.Partial("_DanhMuc")
    </section>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @Html.Partial("_Footer")
        </footer>
    </div>
    <script src="~/Lib/js/jquery-3.3.1.min.js"></script>
    <script src="~/Lib/js/bootstrap.min.js"></script>
    <script src="~/Lib/js/jquery.nice-select.min.js"></script>
    <script src="~/Lib/js/jquery-ui.min.js"></script>
    <script src="~/Lib/js/jquery.slicknav.js"></script>
    <script src="~/Lib/js/mixitup.min.js"></script>
    <script src="~/Lib/js/owl.carousel.min.js"></script>
    <script src="~/Lib/js/main.js"></script>

</body>
</html>

KLTN_FreshShop/Views/Shared/_TopMenu.cshtml
@using KLTN_FreshShop.Models;
<div class="container">
    <div class="row">
        <div class="col-lg-2">
            <div class="header__logo">
                <a href="@Url.Action("Index","Home")"><img src="~/Lib/img/logotps.png" alt="Image_Good-Market"></a>
            </div>
        </div>
        <div class="col-lg-8">
            <nav class="header__menu">
                <ul>
                    <li>
                        <a href="#">Cửa hàng <i class="fa fa-caret-down"></i> </a>
                        <ul class="header__menu__dropdown">
                            <li><a href="#">102 Trường Chinh</a></li>
                            <li><a href="#">08 Trần Hưng Đạo</a></li>
                            <li><a href="#">446 Trần Huy Liệu</a></li>
                            <li><a href="#">228 Lộc Hạ</a></li>
                            <li><a href="#">11 Hoàng Văn Thụ</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">Giới thiệu <i class="fa fa-caret-down"></i></a>
                        <ul class="header__menu__dropdown">
                            <li><a href="@Url.Action("tintuchangngay","TinTuc")">Tin tức</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">Sản phẩm bán chạy <i class="fa fa-caret-down"></i></a>
                        <ul class="header__menu__dropdown">
                            <li><a href="@Url.Action("Chitiet","Sanpham",new { ma = 2015 })">Rau cải ngọt</a></li>
                            <li><a href="@Url.Action("Chitiet","Sanpham",new { ma = 2011 })">Khoai lang Đà Lạt</a></li>
                            <li><a href="@Url.Action("Chitiet","Sanpham",new { ma = 2022 })">Ba chỉ lợn quế</a></li>
                            <li><a href="@Url.Action("Chitiet","Sanpham",new { ma = 2038 })">Ổi Phúc Lợi</a></li>
                            <li><a href="@Url.Action("Chitiet","Sanpham",new { ma = 2047 })">Trứng gà quê</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">Tư vấn dinh dưỡng <i class="fa fa-caret-down"></i></a>
                        <ul class="header__menu__dropdown">
                            <li><a href="@Url.Action("chomebau","TinTuc")">Cho mẹ bầu</a></li>
                            <li><a href="#">Cho trẻ nhỏ</a></li>
                            <li><a href="#">Cho người dậy thì</a></li>
                            <li><a href="#">Cho người trưởng thành</a></li>
                            <li><a href="#">Cho người già</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
        <div class="col-lg-2">
            <div class="header__cart">
                @{
                    List<GioHang> dsgh = (List<GioHang>)Session["dsgh"];
                }
                <ul>
                    @*<li><a href="#"><i class="fa fa-heart"></i> <span>0</span></a></li>*@
                    @if (dsgh != null)
                    {
                        <li><a href="@Url.Action("XemGioHang","GioHang")"><i class="fa fa-shopping-bag"></i> <span>@dsgh.Count</span></a></li>
                    }
                    else
                    {
                        <li><a href="#"><i class="fa fa-shopping-cart"></i> <span>0</span></a></li>
                    }
                </ul>
                @if (dsgh != null)
                {
                    var tongtien = 0.0;
                    foreach (var item in dsgh)
                    {
                        if (item.Spham.KhuyenMai == null)
                        {
                            tongtien = tongtien + (double)item.Spham.Gia * item.SoLuong;
                        }
                        else
                        {
                            double km = Convert.ToDouble(item.Spham.Gia * (100 - item.Spham.KhuyenMai) / 100);
                            double km1 = km * item.SoLuong;
                            tongtien = tongtien + km1;
                        }

                    }
                    <div class="header__cart__price">
                        Giỏ hàng:
                        <span>
                            @Convert.ToDecimal(tongtien).ToString("##,#")
                        </span>
                    </div>


                }
                else
                {
                    <div class="header__cart__price">Giỏ hàng: <span>0.0</span></div>
                }

            </div>
        </div>
    </div>
    <div class="humberger__open">
        <i class="fa fa-bars"></i>
    </div>
</div>

KLTN_FreshShop/Views/Shared/_headerTop.cshtml
<div class="container">
    <div class="row">
        <div class="col-lg-5 col-md-5">
            <div class="header__top__left">
                <ul>
                    <li> <a href="@Url.Action("Index","Home")"><i class="fa fa-home"></i></a>Trang chủ</li>

                </ul>
            </div>
        </div>
        <div class="col-lg-7 col-md-7">
            <div class="header__top__right">
                Cửa hàng
                <div class="header__top__right__social">
                    <a href="#"><i class="fa fa-facebook"></i></a>
                    <a href="#"><i class="fa fa-google"></i></a>
                    <a href="#"><i class="fa fa-youtube"></i></a>
                </div>
                <div class="header__top__right__language">
                    <img src="~/Lib/img/vietnam.png" alt="">
                    <div>Tiếng Việt</div>
                    <span class="arrow_carrot-down"></span>
                    <ul>
                        <li><a href="#">Tiếng Việt</a></li>
                        <li><a href="#">English</a></li>
                    </ul>
                </div>
                @if (Session["ten"] == null)
                {
                    <div class="header__top__right__auth">
                        <a href="@Url.Action("dangnhap", "TaiKhoan")"> <i class="fa fa-user"></i> Đăng nhập</a> | <a href="@Url.Action("dangky", "TaiKhoan")">Đăng ký</a>
                    </div>
                }
                else
                {
                    <div class="header__top__right__language">
                        <div><i class="fa fa-user"></i>  @Session["ten"]</div>
                        <span class="arrow_carrot-down"></span>
                        <ul>

                            <li><a href="@Url.Action("LogOut", "Home")">Thoát</a></li>
                        </ul>
                    </div>
                }
            </div>
        </div>
    </div>
</div>