KLTN_FreshShop/Models/LoaiSP.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLTN_FreshShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiSP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiSP()
        {
            this.SPs = new HashSet<SP>();
        }
    
        public int Ma { get; set; }
        public string Ten { get; set; }
        public string Mota { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SP> SPs { get; set; }
    }
}

KLTN_FreshShop/Areas/Admin/Controllers/LoaiSPsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using System.Net;
using KLTN_FreshShop.Models;
using PagedList;

namespace KLTN_FreshShop.Areas.Admin.Controllers
{
    public class LoaiSPsController : Controller
    {
        private KLTNEntities db = new KLTNEntities();
        // GET: Admin/LoaiSP
        public ActionResult Timkiem(int? page)
        {

            if (page == null)
            {
                page = 1;
            }
            int pageSize = 2;
            int pageNumber = (page ?? 1);
            //var sPs = db.SPs.Include(s => s.LoaiSP);
            return View(db.LoaiSPs.OrderByDescending(s => s.Ma).ToPagedList(pageNumber, pageSize));
        }
        [HttpPost]
        public ActionResult Timkiem(int? page, string keyword)
        {
            var dssp = db.LoaiSPs.Where(s => s.Ten.Contains(keyword)).ToList();
            if (page == null)
            {
                page = 1;
            }
            int pageSize = 2;
            int pageNumber = (page ?? 1);
            return View(dssp.OrderByDescending(s => s.Ma).ToPagedList(pageNumber, pageSize));
        }
        public ActionResult Index(int? page)
        {
            if (Session["nd"] != null)
            {
                if (page == null)
                {
                    page = 1;
                }
                int pageSize = 5;
                int pageNumber = (page ?? 1);
                //var sps = db.LoaiSPs.Include(s => s.Ma);
                return View(db.LoaiSPs.OrderByDescending(s => s.Ma).ToPagedList(pageNumber, pageSize));
            }
            return RedirectToAction("Login", "Default");

        }
        // GET: admin/LoaiSPs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LoaiSP loaiSP = db.LoaiSPs.Find(id);
            if (loaiSP == null)
            {
                return HttpNotFound();
            }
            return View(loaiSP);
        }

        // GET: admin/LoaiSPs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: admin/LoaiSPs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Ma,Ten,Mota")] LoaiSP loaiSP)
        {
            if (ModelState.IsValid)
            {
                db.LoaiSPs.Add(loaiSP);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(loaiSP);
        }

        // GET: admin/LoaiSPs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LoaiSP loaiSP = db.LoaiSPs.Find(id);
            if (loaiSP == null)
            {
                return HttpNotFound();
            }
            return View(loaiSP);
        }

        // POST: admin/LoaiSPs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Ma,Ten,Mota")] LoaiSP loaiSP)
        {
            if (ModelState.IsValid)
            {
                db.Entry(loaiSP).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(loaiSP);
        }

        // GET: admin/LoaiSPs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LoaiSP loaiSP = db.LoaiSPs.Find(id);
            if (loaiSP == null)
            {
                return HttpNotFound();
            }
            return View(loaiSP);
        }

        // POST: admin/LoaiSPs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            LoaiSP loaiSP = db.LoaiSPs.Find(id);
            db.LoaiSPs.Remove(loaiSP);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KLTN_FreshShop/Areas/Admin/Views/LoaiSPs/Create.cshtml
@model Doan_ChuyenMon.Models.LoaiSP

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Thêm Loại Sản Phẩm</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Tên loại sản phẩm</label>
            <div class="col-md-10">
                <input type="text" name="ten" class="form-control" required placeholder="Nhập tên của loại" />
                @*@Html.EditorFor(model => model.ten, new { htmlAttributes = new { @class = "form-control" } })*@
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Mota, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mota, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mota, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm mới" class="btn btn-success" />
            </div>
        </div>
    </div>
}
<div>
    <a href="@Url.Action("Create","LoaiSPs")" class="btn btn-success">Trở về danh sách</a>
</div>

KLTN_FreshShop/Areas/Admin/Views/LoaiSPs/Delete.cshtml
@model Doan_ChuyenMon.Models.LoaiSP

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Xoá loại sản phẩm</h2>
<div>
    <dl class="dl-horizontal">
        <dt>
            Tên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ten)
        </dd>

        <dt>
            Mô tả
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mota)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-success" />
            <a href="@Url.Action("Create","LoaiSPs")" class="btn btn-success">Trở về danh sách</a>
        </div>
    }
</div>

KLTN_FreshShop/Areas/Admin/Views/LoaiSPs/Details.cshtml
@model Doan_ChuyenMon.Models.LoaiSP

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Chi tiết loại sản phẩm</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            Tên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ten)
        </dd>

        <dt>
            Mô tả
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mota)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Sửa", "Edit", new { id = Model.Ma })
    <a href="@Url.Action("Create","LoaiSPs")" class="btn btn-success">Trở về danh sách</a>
</p>

KLTN_FreshShop/Areas/Admin/Views/LoaiSPs/Edit.cshtml
@model Doan_ChuyenMon.Models.LoaiSP

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Sửa thông tin sản phẩm</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })*@
        @Html.HiddenFor(model => model.Ma)

        <div class="form-group">
            <label class="control-label col-md-2">Tên loại sản phẩm</label>
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.ten, new { htmlAttributes = new { @class = "form-control" } })*@
                <input type="text" value="@Model.Ten" name="ten" class="form-control" required />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Mô tả</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Mota, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Create","LoaiSPs")" class="btn btn-success">Trở về danh sách</a>
</div>

KLTN_FreshShop/Areas/Admin/Views/LoaiSPs/Index.cshtml
@model PagedList.IPagedList<Doan_ChuyenMon.Models.LoaiSP>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Danh sách loại sản phẩm</h2>

<p>
    <a href="@Url.Action("Create","LoaiSPs")" class="btn btn-success">Thêm loại sản phẩm</a>
</p>
<table class="table">
    <tr>
        @*<th>
                @Html.DisplayNameFor(model => model.Ten)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mota)
            </th>*@
        <th>
            Tên
        </th>
        <th>
            Mô tả
        </th>
        @*<th>
                Chức năng
            </th>*@
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Ten)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mota)
            </td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.Ma }) |
                @Html.ActionLink("Chi tiết", "Details", new { id = item.Ma }) |
                @Html.ActionLink("Xoá", "Delete", new { id = item.Ma })
            </td>
        </tr>
    }

</table>
<div class="text-center">@Html.PagedListPager(Model, page => Url.Action("Index", "LoaiSPs", new { page }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "get", UpdateTargetId = "sp_area" }))</div>

KLTN_FreshShop/Areas/Admin/Views/LoaiSPs/Timkiem.cshtml
@model IEnumerable<Doan_ChuyenMon.Models.LoaiSP>

@{
    ViewBag.Title = "Timkiem";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<h2>Tìm kiếm loại sản phẩm</h2>
<form class="form-inline" action="@Url.Action("Timkiem","LoaiSPs")" method="post">
    <div class="form-group">
        <label for="exampleInputName2">Nhập thông tin cần tìm</label>
        <input type="text" class="form-control" name="keyword" id="example" placeholder="nhập tên Loại sp cần tìm">
        <button type="submit" class="btn btn-default">Tìm</button>
    </div>

</form>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Ten)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Mota)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Ten)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mota)
            </td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.Ma }) |
                @Html.ActionLink("Chi tiết", "Details", new { id = item.Ma }) |
                @Html.ActionLink("Xoá", "Delete", new { id = item.Ma })
            </td>
        </tr>
    }

</table>