KLTN_FreshShop/Models/DonHang.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLTN_FreshShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
        }
    
        public int Ma { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public Nullable<decimal> PhiGiao { get; set; }
        public string TenNguoiNhan { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string Email { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string PhuongThucTT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}

KLTN_FreshShop/Areas/Admin/Controllers/DonHangsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KLTN_FreshShop.Models;

namespace KLTN_FreshShop.Areas.Admin.Controllers
{
    public class DonHangsController : Controller
    {
        private KLTNEntities db = new KLTNEntities();
        // GET: Admin/Donhang
        public ActionResult Index()
        {
            var donHangs = db.DonHangs.Include(d => d.KhachHang);
            return View(donHangs.ToList());
        }

        // GET: admin/DonHangs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonHang donHang = db.DonHangs.Find(id);
            if (donHang == null)
            {
                return HttpNotFound();
            }
            return View(donHang);
        }

        // GET: admin/DonHangs/Create
        public ActionResult Create()
        {
            ViewBag.MaKH = new SelectList(db.KhachHangs, "Ma", "Ten");
            return View();
        }

        // POST: admin/DonHangs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Ma,MaKH,NgayDat,NgayGiao,PhiGiao,TenNguoiNhan,DiaChi,DienThoai,Email,TrangThai,PhuongThucTT")] DonHang donHang)
        {
            if (ModelState.IsValid)
            {
                db.DonHangs.Add(donHang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaKH = new SelectList(db.KhachHangs, "Ma", "Ten", donHang.MaKH);
            return View(donHang);
        }

        // GET: admin/DonHangs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonHang donHang = db.DonHangs.Find(id);
            if (donHang == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaKH = new SelectList(db.KhachHangs, "Ma", "Ten", donHang.MaKH);
            return View(donHang);
        }

        // POST: admin/DonHangs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Ma,MaKH,NgayDat,NgayGiao,PhiGiao,TenNguoiNhan,DiaChi,DienThoai,Email,TrangThai,PhuongThucTT")] DonHang donHang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(donHang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaKH = new SelectList(db.KhachHangs, "Ma", "Ten", donHang.MaKH);
            return View(donHang);
        }

        // GET: admin/DonHangs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonHang donHang = db.DonHangs.Find(id);
            if (donHang == null)
            {
                return HttpNotFound();
            }
            return View(donHang);
        }

        // POST: admin/DonHangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var qr = from ct in db.ChiTietDonHangs where ct.MaDH == id select ct;
            int idctdh = qr.Count();
            for (int i = 0; i < idctdh; i++)
            {
                ChiTietDonHang ctdh = new ChiTietDonHang();
                ctdh = qr.FirstOrDefault();
                //ChiTietDonHang ctdh = db.ChiTietDonHangs.Find(id);
                db.ChiTietDonHangs.Remove(ctdh);
                db.SaveChanges();
            }

            DonHang donHang = db.DonHangs.Find(id);
            db.DonHangs.Remove(donHang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KLTN_FreshShop/Areas/Admin/Views/DonHangs/Create.cshtml
@model Doan_ChuyenMon.Models.DonHang

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Thêm đơn hàng mới</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <label class="control-label col-md-2">Người nhận</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenNguoiNhan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenNguoiNhan, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Ngày đặt</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayDat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayDat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Ngày giao</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayGiao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayGiao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Phí giao</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhiGiao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhiGiao, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <label class="control-label col-md-2">Địa chỉ</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Điện thoại</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DienThoai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DienThoai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Email</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Trạng thái</label>
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.TrangThai)
                    @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Phương thức thanh toán</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhuongThucTT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhuongThucTT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Index","DonHangs")" class="btn btn-success">Trở về danh sách</a>
</div>

KLTN_FreshShop/Areas/Admin/Views/DonHangs/Delete.cshtml
@model Doan_ChuyenMon.Models.DonHang

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DonHang</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NgayDat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayDat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayGiao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayGiao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhiGiao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhiGiao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenNguoiNhan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNguoiNhan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DienThoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DienThoai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrangThai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrangThai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhuongThucTT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhuongThucTT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KhachHang.Ten)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KhachHang.Ten)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

KLTN_FreshShop/Areas/Admin/Views/DonHangs/Details.cshtml
@model Doan_ChuyenMon.Models.DonHang

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>DonHang</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NgayDat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayDat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayGiao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayGiao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhiGiao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhiGiao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenNguoiNhan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNguoiNhan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DienThoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DienThoai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrangThai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrangThai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhuongThucTT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhuongThucTT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KhachHang.Ten)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KhachHang.Ten)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Ma }) |
    @Html.ActionLink("Back to List", "Index")
</p>

KLTN_FreshShop/Areas/Admin/Views/DonHangs/Edit.cshtml
@model Doan_ChuyenMon.Models.DonHang

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Sửa thông tin đơn hàng</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Ma)

        <div class="form-group">
            <label class="control-label col-md-2">Người nhận</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenNguoiNhan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenNguoiNhan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Ngày đặt</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayDat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayDat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Ngày giao</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayGiao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayGiao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Phí giao</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhiGiao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhiGiao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Địa chỉ</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Điện thoại</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DienThoai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DienThoai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Email</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Trạng thái</label>
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.TrangThai)
                    @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Phương thức thanh toán</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhuongThucTT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhuongThucTT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Index","DonHangs")" class="btn btn-success">Trở về danh sách</a>
</div>

KLTN_FreshShop/Areas/Admin/Views/DonHangs/Index.cshtml
@model IEnumerable<Doan_ChuyenMon.Models.DonHang>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Danh sách đơn hàng</h2>
<p>
    <a href="@Url.Action("Create","DonHangs")" class="btn btn-success">Thêm đơn hàng mới</a>
</p>
<table class="table">
    <tr>
        <th>
            Tên người nhận
        </th>
        <th>
            Ngày đặt
        </th>
        <th>
            Ngày giao
        </th>
        <th>
            Phí giao
        </th>

        <th>
            Địa chỉ
        </th>
        <th>
            Điện thoại
        </th>
        <th>
            Email
        </th>
        <th>
            Trạng thái
        </th>
        <th>
            Phương thức thanh toán
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TenNguoiNhan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayDat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayGiao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhiGiao)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.DiaChi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DienThoai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TrangThai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhuongThucTT)
            </td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.Ma }) |
                @Html.ActionLink("Xoá", "Delete", new { id = item.Ma })
            </td>
        </tr>
    }

</table>