KLTN_FreshShop/Models/TinTuc.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLTN_FreshShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public int Ma { get; set; }
        public Nullable<int> MaCM { get; set; }
        public string MotaNgan { get; set; }
        public string Mota { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public string Anh { get; set; }
        public string NguoiDang { get; set; }
        public Nullable<bool> TieuBieu { get; set; }
        public string LoaiTin { get; set; }
        public string TieuDe { get; set; }
    
        public virtual ChuyenMuc ChuyenMuc { get; set; }
    }
}

KLTN_FreshShop/Areas/Admin/Controllers/TinTucsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using KLTN_FreshShop.Models;
using System.Data;
using System.Data.Entity;
using System.Net;

namespace KLTN_FreshShop.Areas.Admin.Controllers
{
    public class TinTucsController : Controller
    {
        private KLTNEntities db = new KLTNEntities();
        // GET: Admin/TinTucs
        public ActionResult Timkiem(int? page)
        {

            if (page == null)
            {
                page = 1;
            }
            int pageSize = 2;
            int pageNumber = (page ?? 1);
            //var sPs = db.SPs.Include(s => s.LoaiSP);
            return View(db.TinTucs.OrderByDescending(s => s.Ma).ToPagedList(pageNumber, pageSize));
        }
        [HttpPost]
        public ActionResult Timkiem(int? page, string keyword)
        {
            var dssp = db.TinTucs.Where(s => s.MotaNgan.Contains(keyword)).ToList();
            ViewBag.dem = dssp.Count();
            if (page == null)
            {
                page = 1;
            }
            int pageSize = 2;
            int pageNumber = (page ?? 1);
            return View(dssp.OrderByDescending(s => s.Ma).ToPagedList(pageNumber, pageSize));
        }
        public ActionResult Index()
        {
            if (Session["nd"] != null)
            {
                var tinTucs = db.TinTucs.Include(t => t.ChuyenMuc);
                return View(tinTucs.ToList());
            }
            return RedirectToAction("Login", "Default");

        }

        // GET: admin/TinTucs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TinTuc tinTuc = db.TinTucs.Find(id);
            if (tinTuc == null)
            {
                return HttpNotFound();
            }
            return View(tinTuc);
        }

        // GET: admin/TinTucs/Create
        public ActionResult Create()
        {
            ViewBag.MaCM = new SelectList(db.ChuyenMucs, "Ma", "Ten");
            return View();
        }

        // POST: admin/TinTucs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "Ma,MaCM,MotaNgan,Mota,NgayDang,Anh,NguoiDang,TieuBieu,LoaiTin")] TinTuc tinTuc)
        {
            if (ModelState.IsValid)
            {
                db.TinTucs.Add(tinTuc);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaCM = new SelectList(db.ChuyenMucs, "Ma", "Ten", tinTuc.MaCM);
            return View(tinTuc);
        }

        // GET: admin/TinTucs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TinTuc tinTuc = db.TinTucs.Find(id);
            if (tinTuc == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaCM = new SelectList(db.ChuyenMucs, "Ma", "Ten", tinTuc.MaCM);
            return View(tinTuc);
        }

        // POST: admin/TinTucs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "Ma,MaCM,MotaNgan,Mota,NgayDang,Anh,NguoiDang,TieuBieu,LoaiTin")] TinTuc tinTuc)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tinTuc).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaCM = new SelectList(db.ChuyenMucs, "Ma", "Ten", tinTuc.MaCM);
            return View(tinTuc);
        }

        // GET: admin/TinTucs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TinTuc tinTuc = db.TinTucs.Find(id);
            if (tinTuc == null)
            {
                return HttpNotFound();
            }
            return View(tinTuc);
        }

        // POST: admin/TinTucs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TinTuc tinTuc = db.TinTucs.Find(id);
            db.TinTucs.Remove(tinTuc);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KLTN_FreshShop/Controllers/TinTucController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KLTN_FreshShop.Models;

namespace KLTN_FreshShop.Controllers
{
    public class TinTucController : Controller
    {
        KLTNEntities db = new KLTNEntities();
        // GET: TinTuc
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult _tintuc()
        {
            ViewBag.dsTin = db.TinTucs.Where(s => s.TieuBieu == true && s.LoaiTin==null).ToList();
            return PartialView();
        }
        public PartialViewResult chomebau()
        {
            ViewBag.dsTinchomebau = db.TinTucs.Where(s => s.LoaiTin == "chomebau").ToList();
            return PartialView();
        }
        public PartialViewResult tintuchangngay()
        {
            ViewBag.dsTinTucHangNgay = db.TinTucs.Where(s => s.LoaiTin == "TinTucHangNgay").ToList();
            return PartialView();
        }
        public ActionResult timkiem(String txtsearch)
        {
            var qr = db.TinTucs.Where(s => s.MotaNgan.Contains(txtsearch)).ToList();
            ViewBag.kq = qr.Count();
            return View(qr);
        }
        public ActionResult Chitiettin(int ma)
        {
            var tint = db.TinTucs.Find(ma);
            ViewBag.tint = db.TinTucs.Where(s => s.LoaiTin == tint.LoaiTin).Take(4).ToList();
            return View(tint);
        }
    }
}

KLTN_FreshShop/Areas/Admin/Views/TinTucs/Create.cshtml
@model Doan_ChuyenMon.Models.TinTuc

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Thêm tin tức mới</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Chuyên mục</label>
            <div class="col-md-10">
                @Html.DropDownList("MaCM", null, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Tên</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.MotaNgan, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Mô tả</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Mota, new { htmlAttributes = new { @class = "form-control" } })
                <script type="text/javascript">
                    CKEDITOR.replace("Mota")
                </script>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Ngày đăng</label>
            <div class="col-md-10">
                <input type="date" name="NgayDang" class="form-control" id="Ngaydang" />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Ảnh</label>
            <div class="col-md-10">
                <div class="col-md-4">
                    <input type="text" name="Anh" id="Anh" class="form-control" />
                </div>
                <div class="col-md-2">
                    <input type="button" class="btn btn-default" id="browse" value="browse" />
                </div>
                <div class="col-md-3">
                    <img src="#" id="anhtin" width="50" height="50" />
                </div>
            </div>
        </div>

        <script type="text/javascript">
            $("#browse").click(function () {
                var finder = new CKFinder();
                finder.selectActionFunction = function (fileUrl) {;
                    $("#Anh").val(fileUrl);
                    $("#anhtin").attr("src", fileUrl);
                }
                finder.popup();
            });

        </script>

        <div class="form-group">
            <label class="control-label col-md-2">Người đăng</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.NguoiDang, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Tiêu biểu</label>
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.TieuBieu)
                </div>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Loại tin</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.LoaiTin, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm mới" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Index","TinTucs")" class="btn btn-success">Trở về danh sách</a>
</div>

KLTN_FreshShop/Areas/Admin/Views/TinTucs/Delete.cshtml
@model Doan_ChuyenMon.Models.TinTuc

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Xoá tin tức</h2>
<div>
    <dl class="dl-horizontal">
        <dt>
            Mã CM
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaCM)
        </dd>

        <dt>
            Mô tả ngắn
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MotaNgan)
        </dd>

        <dt>
            Mô tả
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mota)
        </dd>

        <dt>
            Ngày đăng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayDang)
        </dd>

        <dt>
            Ảnh
        </dt>

        <dd>
            <img src="@Html.DisplayFor(model => model.Anh)" height="100px" width="100px" />
        </dd>

        <dt>
            Người đăng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NguoiDang)
        </dd>

        <dt>
            Tiêu biểu
        </dt>

        <dd>
            if(@Html.DisplayFor(model => model.TieuBieu) ==)
            {
            <span>Tiêu biểu</span>
            }
            else
            {
            Không tiểu biểu
            }
        </dd>

        <dt>
            Loại tin
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiTin)
        </dd>

        <dt>
            Tên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChuyenMuc.Ten)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xoá" class="btn btn-success" />
            <a href="@Url.Action("Index","TinTucs")" class="btn btn-success">Trở về danh sách</a>
        </div>
    }
</div>

KLTN_FreshShop/Areas/Admin/Views/TinTucs/Details.cshtml
@model Doan_ChuyenMon.Models.TinTuc

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>TinTuc</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaCM)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaCM)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MotaNgan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MotaNgan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mota)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mota)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayDang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayDang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Anh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Anh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NguoiDang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NguoiDang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TieuBieu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TieuBieu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoaiTin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiTin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChuyenMuc.Ten)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChuyenMuc.Ten)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Ma }) |
    @Html.ActionLink("Back to List", "Index")
</p>

KLTN_FreshShop/Areas/Admin/Views/TinTucs/Edit.cshtml
@model Doan_ChuyenMon.Models.TinTuc

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Sửa tin tức</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Ma)

        <div class="form-group">
            <b class="control-label col-md-2">Mã CM</b>
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaCM, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaCM, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <b class="control-label col-md-2">Mô tả ngắn</b>
            <div class="col-md-10">
                @Html.EditorFor(model => model.MotaNgan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MotaNgan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Mô tả</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Mota, new { htmlAttributes = new { @class = "form-control" } })
                <script type="text/javascript">
                    CKEDITOR.replace("Mota")
                </script>
            </div>
        </div>

        <div class="form-group">
            <b class="control-label col-md-2">Ngày đăng</b>
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.NgayDang, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NgayDang, "", new { @class = "text-danger" })*@
                <input type="date" required class="form-control" name="Ngaydang" value="@Model.NgayDang" />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Ảnh</label>
            <div class="col-md-10">
                <div class="col-md-4">
                    <input type="text" name="Anh" id="Anh" class="form-control" />
                </div>
                <div class="col-md-2">
                    <input type="button" class="btn btn-default" id="browse" value="browse" />
                </div>
                <div class="col-md-3">
                    <img src="#" id="anhtin" width="50" height="50" />
                </div>
            </div>
        </div>
        <script type="text/javascript">
            $("#browse").click(function () {
                var finder = new CKFinder();
                finder.selectActionFunction = function (fileUrl) {;
                    $("#Anh").val(fileUrl);
                    $("#anhtin").attr("src", fileUrl);
                }
                finder.popup();
            });

        </script>

        <div class="form-group">
            <b class="control-label col-md-2">Người đăng</b>
            <div class="col-md-10">
                @Html.EditorFor(model => model.NguoiDang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NguoiDang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <b class="control-label col-md-2">Tiêu biểu</b>
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.TieuBieu)
                    @Html.ValidationMessageFor(model => model.TieuBieu, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <b class="control-label col-md-2">Loại tin</b>
            <div class="col-md-10">
                @Html.EditorFor(model => model.LoaiTin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LoaiTin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Index","TinTucs")" class="btn btn-success">Trở về danh sách</a>
</div>

KLTN_FreshShop/Areas/Admin/Views/TinTucs/Index.cshtml
@model IEnumerable<Doan_ChuyenMon.Models.TinTuc>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Danh sách tin </h2>

<p>
    <a href="@Url.Action("Create","TinTucs")" class="btn btn-success">Thêm tin mới</a>
</p>
<table class="table">
    <tr>
        <th>
            <label class="control-label col-md-2">Tên Tin</label>
        </th>
        <th>
            <label class="control-label col-md-2">Mô tả</label>
        </th>
        <th>
            <label class="control-label col-md-2">Ngày đăng</label>
        </th>
        <th>
            <label class="control-label col-md-2">Ảnh</label>
        </th>
        <th>
            <label class="control-label col-md-2">Người đăng</label>
        </th>
        <th>
            <label class="control-label col-md-2">Tiêu biểu</label>
        </th>
        <th>
            <label class="control-label col-md-2">Loại tin</label>
        </th>
        <th>Chức năng</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.MotaNgan
            </td>
            <td>
                @Html.Raw(item.Mota)
            </td>
            <td>
                @Convert.ToDateTime(item.NgayDang)
            </td>
            <td>
                <img src="@item.Anh" width="100" height="100" />
            </td>
            <td>
                @item.NguoiDang
            </td>
            <td>

                @if (item.TieuBieu == true)
                {
                    <span>Tiêu biểu</span>
                }
                else
                {
                    <span>Không tiêu biểu</span>
                }

            </td>
            <td>
                @item.LoaiTin
            </td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.Ma }) |
                @Html.ActionLink("Chi Tiết", "Details", new { id = item.Ma }) |
                @Html.ActionLink("Xoá", "Delete", new { id = item.Ma })
            </td>
        </tr>
    }

</table>

KLTN_FreshShop/Areas/Admin/Views/TinTucs/Timkiem.cshtml
@model PagedList.IPagedList<Doan_ChuyenMon.Models.TinTuc>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Timkiem";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Tìm kiếm tin tức</h2>

<form class="form-inline" action="@Url.Action("Timkiem","TinTucs")" method="post">
    <div class="form-group">
        <label for="exampleInputName2">Nhập thông tin</label>
        <input type="text" class="form-control" name="keyword" id="example" placeholder="nhập tiêu đề cần tìm">
        <button type="submit" class="btn btn-default">Tìm</button>
    </div>

</form>
@if (ViewBag.dem > 0)
{
    <table class="table">
        <tr>
            <th>
                Mô tả ngắn
            </th>
            <th>
                Mô tả
            </th>
            <th>
                Ngày đăng
            </th>
            <th>
                Ảnh
            </th>
            <th>
                Người đăng
            </th>
            <th>
                Tiêu biếu
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MotaNgan)
                </td>
                <td>
                    @Html.Raw(item.Mota)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NgayDang)
                </td>
                <td>
                    <img src="@Html.DisplayFor(modelItem => item.Anh)" width="100px" height="100px" />

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NguoiDang)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TieuBieu)
                </td>
                <td>
                    @Html.ActionLink("Sửa", "Edit", new { id = item.Ma }) |
                    @Html.ActionLink("Chi tiết", "Details", new { id = item.Ma }) |
                    @Html.ActionLink("Xoá", "Delete", new { id = item.Ma })
                </td>
            </tr>
        }

    </table>
}
else
{
    <h2 style="text-align:center; color:red">Không tìm thấy tên yêu cầu</h2>
}